name: docker-build-image
on:
  push:
  
    branches: none
      #- master 
      #- develop
  pull_request:
  
    branches: none
      #- master 
      #- develop 
      # Allow to run this workflow on GitHub actions manually
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
      working-directory: microservice-docker
      run: docker build --file Dockerfile -t docker-build-workflow .
