name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build and Test
      run: |
        dotnet build --configuration Release
        dotnet test

    - name: Login to GitHub Packages
      run: echo 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 | docker login ghcr.io -u prateektom --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/prateektom/min-api-docker-ghcr:latest .
        docker push ghcr.io/prateektom/min-api-docker-ghcr:latest
