name: Build and Push Docker Image

on:
  #push:
   # branches: none
     # - master
# allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
env :
    REGISTRY : ghcr.io
    IMAGE_NAME : prateektom/min-api-docker-ghcr
    IMAGE_TAG : latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      # this is used to complete identity changes for the Docker daemon
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

      #login to ghcr.io
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.TOKEN_GIT }} | docker login ghcr.io -u ${{secrets.DOCKER_USERNAME }} --password-stdin


    - name: Build and Test
      run: |
        dotnet build --configuration Release
        dotnet test

    - name: Build Docker Image
      run: docker buildx build -t ghcr.io/${{secrets.DOCKER_USERNAME}}/min-api-docker-ghcr:latest .
      working-directory: microservice-docker
    - name: Push Docker Image to GitHub Packages
       IMAGE_TAG="ghcr.io/${{secrets.DOCKER_USERNAME}}/api-docker-ghcr:$(date +%s)"
      run: |
        docker buildx build --push -t $IMAGE_TAG .
      working-directory: microservice-docker
        echo "::set-output name=image::$IMAGE_TAG"

    - name: Cleanup
      run: docker system prune -f
